/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Conexiones.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import javax.imageio.ImageIO;

/**
 *
 * @author win8
 */
public class interfazEditar extends javax.swing.JFrame {

    static ResultSet res;
    int cont;
    byte[] icono;
    byte[] data;
    Blob blob;
    String filename = null;
    static int estiloCase;
    static int estadoCase;
    static int sedeCase;
    static int tipoCase;
    static int marcaCase;
    static int colorCase;

    public interfazEditar() {
        initComponents();
        entradaColorE.removeAllItems();
        entradaEstadoE.removeAllItems();
        entradaEstiloE.removeAllItems();
        entradaMarcaE.removeAllItems();
        entradaSedeE.removeAllItems();
        entradaTipoE.removeAllItems();
        cargarEstilo();
        cargarEstado();
        cargarColor();
        cargarMarca();
        cargarSede();
        cargarTransmision();
    }

    public void cargarEstilo() {
        res = Conexion.consulta("select * from esquema.Estilo");
        try {
            while (res.next()) {
                entradaEstiloE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void cargarEstado() {
        res = Conexion.consulta("select * from esquema.Estado");
        try {
            while (res.next()) {
                entradaEstadoE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
        }
    }

    public void cargarColor() {
        res = Conexion.consulta("select * from esquema.Color");
        try {
            while (res.next()) {
                entradaColorE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
        }
    }

    public void cargarMarca() {
        res = Conexion.consulta("select * from esquema.Marca");
        try {
            while (res.next()) {
                entradaMarcaE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
        }
    }

    public void cargarSede() {
        res = Conexion.consulta("select * from esquema.Sede");
        try {
            while (res.next()) {
                entradaSedeE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
        }
    }

    public void cargarTransmision() {
        res = Conexion.consulta("select * from esquema.TipoTransmision");
        try {
            while (res.next()) {
                entradaTipoE.addItem(res.getString(2));
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fotoVehiculo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        entradaCostoE = new javax.swing.JTextField();
        entradaAñoE = new javax.swing.JTextField();
        entradaKiloE = new javax.swing.JTextField();
        entradaCapacidadE = new javax.swing.JTextField();
        entradaMaletasE = new javax.swing.JTextField();
        entradaVinE = new javax.swing.JTextField();
        entradaPuertasE = new javax.swing.JTextField();
        entradaEstiloE = new javax.swing.JComboBox<>();
        entradaEstadoE = new javax.swing.JComboBox<>();
        entradaSedeE = new javax.swing.JComboBox<>();
        entradaTipoE = new javax.swing.JComboBox<>();
        entradaMarcaE = new javax.swing.JComboBox<>();
        entradaColorE = new javax.swing.JComboBox<>();
        entradasMpgE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        entradaPlacaEditar = new javax.swing.JTextField();
        txtruta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese la placa del vehiculo y los nuevos datos");

        jLabel2.setText("Costo por día:");

        jLabel3.setText("Año:");

        jLabel4.setText("Kilometraje:");

        jLabel5.setText("Id Estilo:");

        jLabel6.setText("Id Estado:");

        jLabel7.setText("Numero de VIN:");

        jLabel8.setText("Numero de Puertas:");

        jLabel9.setText("MPG:");

        jLabel10.setText("Id Sede:");

        jLabel11.setText("Id Tipo de Tranmisión:");

        jLabel12.setText("Id Marca:");

        jLabel13.setText("Id Color:");

        jLabel14.setText("Capacidad:");

        jLabel15.setText("Cantidad de Maletas:");

        jButton1.setText("Ingresar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Foto:");

        fotoVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Cargar Foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        entradaAñoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaAñoEActionPerformed(evt);
            }
        });

        entradaCapacidadE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCapacidadEActionPerformed(evt);
            }
        });

        entradaMaletasE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaMaletasEActionPerformed(evt);
            }
        });

        entradaVinE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaVinEActionPerformed(evt);
            }
        });

        entradaEstiloE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaEstadoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaSedeE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaTipoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaMarcaE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradaColorE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        entradasMpgE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradasMpgEActionPerformed(evt);
            }
        });

        jLabel18.setText("Placa:");

        txtruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(entradaVinE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaPuertasE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaEstadoE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaEstiloE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaKiloE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaAñoE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradaCostoE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entradasMpgE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(entradaPlacaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtruta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(entradaCapacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(70, 70, 70)
                                            .addComponent(entradaColorE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(entradaMaletasE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(entradaSedeE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(fotoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addGap(74, 74, 74)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entradaTipoE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaMarcaE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(entradaSedeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(entradaPlacaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(entradaTipoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaCostoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(entradaMarcaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(entradaAñoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(entradaColorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(entradaKiloE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(entradaCapacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaEstiloE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(entradaMaletasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(entradaEstadoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(entradaVinE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(entradaPuertasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(entradasMpgE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fotoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (entradaPlacaEditar.getText().isEmpty() || entradaCostoE.getText().isEmpty() || entradaAñoE.getText().isEmpty() || entradaKiloE.getText().isEmpty()
                || entradaVinE.getText().isEmpty() || entradaPuertasE.getText().isEmpty() || entradasMpgE.getText().isEmpty() || entradaCapacidadE.getText().isEmpty()
                || entradaMaletasE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            switch(entradaEstiloE.getSelectedItem().toString()){
                case "Compacto": 
                    estiloCase=1;
                    break;
                case "Pickup": 
                    estiloCase=2;
                    break;    
                case "Intermedio": 
                    estiloCase=3;
                    break;    
                case "SUV": 
                    estiloCase=4;
                    break;
                case "Mini-van": 
                    estiloCase=5;
                    break;
                case "Convertible": 
                    estiloCase=6;
                    break;
                case "Económico": 
                    estiloCase=7;
                    break;
            }
            switch(entradaEstadoE.getSelectedItem().toString()){
                case "Activo": 
                    estadoCase=1;
                    break;
                case "Mantenimiento": 
                    estadoCase=2;
                    break;    
                case "Inactivo": 
                    estadoCase=3;
                    break;       
            }
            switch(entradaSedeE.getSelectedItem().toString()){
                case "Escazú": 
                    sedeCase=1;
                    break;
                case "Moravia": 
                    sedeCase=2;
                    break;    
                case "Peréz Zeledón": 
                    sedeCase=3;
                    break;    
                case "Grecia": 
                    sedeCase=4;
                    break;
                case "Paraíso": 
                    sedeCase=5;
                    break;
                case "Heredia": 
                    sedeCase=6;
                    break;
                case "Belén": 
                    sedeCase=7;
                    break;
                case "Liberia": 
                    sedeCase=8;
                    break;
                case "Quepos": 
                    sedeCase=9;
                    break;
                case "Limón": 
                    sedeCase=10;
                    break;
                case "Cartago": 
                    sedeCase=11;
                    break;
                case "San Pedro": 
                    sedeCase=12;
                    break;
                case "San Carlos": 
                    sedeCase=13;
                    break;
                case "Alajuela": 
                    sedeCase=14;
                    break;
                case "Zapote": 
                    sedeCase=15;
                    break;
                case "Tres Ríos": 
                    sedeCase=16;
                    break;
                case "Golfito": 
                    sedeCase=17;
                    break;
                case "Tortuguero": 
                    sedeCase=18;
                    break;
                case "Santa Cruz": 
                    sedeCase=19;
                    break;
                case "Desamparados": 
                    sedeCase=20;
                    break;
                case "San José": 
                    sedeCase=21;
                    break;
                case "Tarrazú": 
                    sedeCase=22;
                    break;
            }
            switch(entradaTipoE.getSelectedItem().toString()){
                case "Manual": 
                    tipoCase=1;
                    break;
                case "Automático": 
                    tipoCase=2;
                    break;    
                case "Híbrido": 
                    tipoCase=3;
                    break;       
            }
            switch(entradaMarcaE.getSelectedItem().toString()){
                case "Toyota": 
                    marcaCase=1;
                    break;
                case "Suzuki": 
                    marcaCase=2;
                    break;    
                case "Mitsubishi": 
                    marcaCase=3;
                    break;
                case "BMW": 
                    marcaCase=4;
                    break; 
                case "Ford": 
                    marcaCase=5;
                    break;
                case "Volkswagen": 
                    marcaCase=6;
                    break;
                case "Audi": 
                    marcaCase=7;
                    break;
                case "Nissan": 
                    marcaCase=8;
                    break;
                case "Jeep": 
                    marcaCase=9;
                    break;
                case "Volvo": 
                    marcaCase=10;
                    break;
            }
            switch(entradaColorE.getSelectedItem().toString()){
                case "Rojo": 
                    colorCase=1;
                    break;
                case "Verde": 
                    colorCase=2;
                    break;    
                case "Azul": 
                    colorCase=3;
                    break;
                case "Negro": 
                    colorCase=4;
                    break; 
                case "Gris": 
                    colorCase=5;
                    break;
                case "Blanco": 
                    colorCase=6;
                    break;
                case "Amarillo": 
                    colorCase=7;
                    break;
                case "Dorado": 
                    colorCase=8;
                    break;
                case "Cafe": 
                    colorCase=9;
                    break;
                case "Morado": 
                    colorCase=10;
                    break;
            }
            try {

                PreparedStatement pps = Conexion.getConexion().prepareStatement("update esquema.Vehiculo set numeroVIN='" + entradaVinE.getText() + "', costoDia='" + entradaCostoE.getText()
                        + "', año='" + entradaAñoE.getText() + "', capacidadPersonas='" + entradaCapacidadE.getText() + "', numeroPuertas='" + entradaPuertasE.getText() + "', cantidadMaletas='" + entradaMaletasE.getText()
                        + "', mpg='" + entradasMpgE.getText() + "', kilometraje='" + entradaKiloE.getText() + "', foto= CONVERT(VARBINARY(max), '" + data + "'), idTransmision='" + Integer.toString(tipoCase) + "', idColor='" + Integer.toString(colorCase)
                        + "', idMarca='" + Integer.toString(marcaCase) + "', idEstado='" + Integer.toString(estadoCase) + "', idEstilo='" + Integer.toString(estiloCase)
                        + "', idSede='" + Integer.toString(sedeCase) + "' where placa ='" + entradaPlacaEditar.getText() + "'");
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Los datos ha sido modificados");

            } catch (SQLException e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void entradaAñoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaAñoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaAñoEActionPerformed

    private void entradaVinEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaVinEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaVinEActionPerformed

    private void entradaCapacidadEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCapacidadEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCapacidadEActionPerformed

    private void entradaMaletasEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaMaletasEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaMaletasEActionPerformed

    private void entradasMpgEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradasMpgEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradasMpgEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png");
        archivo.setFileFilter(fil);
        int ventana = archivo.showOpenDialog(null);

        if (ventana == JFileChooser.APPROVE_OPTION) {

            File file = archivo.getSelectedFile();

            txtruta.setText(String.valueOf(file));

            Image foto = getToolkit().getImage(txtruta.getText());

            foto = foto.getScaledInstance(fotoVehiculo.getWidth(), fotoVehiculo.getHeight(), Image.SCALE_DEFAULT);

            fotoVehiculo.setIcon(new ImageIcon(foto));

            BufferedImage bImagen = null;
            try {
                bImagen = ImageIO.read(new File(txtruta.getText()));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            try {
                ImageIO.write(bImagen, "jpg", bos);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            data = bos.toByteArray();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaAñoE;
    private javax.swing.JTextField entradaCapacidadE;
    private javax.swing.JComboBox<String> entradaColorE;
    private javax.swing.JTextField entradaCostoE;
    private javax.swing.JComboBox<String> entradaEstadoE;
    private javax.swing.JComboBox<String> entradaEstiloE;
    private javax.swing.JTextField entradaKiloE;
    private javax.swing.JTextField entradaMaletasE;
    private javax.swing.JComboBox<String> entradaMarcaE;
    private javax.swing.JTextField entradaPlacaEditar;
    private javax.swing.JTextField entradaPuertasE;
    private javax.swing.JComboBox<String> entradaSedeE;
    private javax.swing.JComboBox<String> entradaTipoE;
    private javax.swing.JTextField entradaVinE;
    private javax.swing.JTextField entradasMpgE;
    private javax.swing.JLabel fotoVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
