/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Conexiones.Procedimientos;
import Maps.*;
import prograbases1.*;
import Conexiones.*;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author win8
 */
public class interfazReservaCompleta extends javax.swing.JFrame {

    java.util.Date copiaFechaRecogida;
    java.sql.Date copiaFecha1;
    java.util.Date copiaFechaEntrega;
    java.sql.Date copiaFecha2;
    public static String correoCliente;
    static ResultSet res;
    int cont;
    public int idreserva;
    public int idfactura;
    public int idRecorrido;
    java.sql.Date fechaE;
    public String copiaSedeRecogida;
    public String copiaSedeEntrega;
    public String copiaFechaR;
    public String copiaFechaE;
    public String cedulaReserva;
    public String copiaPlacaR;
    public float costoTotal;
    public int cantidadDias;
    public static float costoReserva;
    public String copiaFechaSolicitud;
    public static String informacionReserva;
    SwingBrowser browser = new SwingBrowser();

    /**
     * Creates new form interfazReservaCompleta
     */
    public interfazReservaCompleta() {
        initComponents();
        entradaSedeRecogida.removeAllItems();
        entradaSedeEntrega.removeAllItems();
        cargarSede();
    }

    public void cargarSede() {
        res = Conexiones.Conexion.consulta("select * from esquema.Sede");
        try {
            while (res.next()) {
                entradaSedeRecogida.addItem(res.getString(1));
                entradaSedeEntrega.addItem(res.getString(1));
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaCedulaReserva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resultadoCedula = new javax.swing.JLabel();
        resultadoNombre = new javax.swing.JLabel();
        resultadoApellido1 = new javax.swing.JLabel();
        resultadoApellido2 = new javax.swing.JLabel();
        resultadoCorreo = new javax.swing.JLabel();
        resultadoTelefono = new javax.swing.JLabel();
        resultadoProvincia = new javax.swing.JLabel();
        resultadoCanton = new javax.swing.JLabel();
        resultadoDistrito = new javax.swing.JLabel();
        resultadoSeñas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        entradaFechaRecogida = new com.toedter.calendar.JDateChooser();
        entradaFechaEntrega = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        entradaWifi = new javax.swing.JCheckBox();
        entradaAsistencia = new javax.swing.JCheckBox();
        entradaAsiento = new javax.swing.JCheckBox();
        entradaCobertura = new javax.swing.JCheckBox();
        entradaGPS = new javax.swing.JCheckBox();
        entradaSedeRecogida = new javax.swing.JComboBox<>();
        entradaSedeEntrega = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        entradaCapacidadFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        entradaPrecioMenor = new javax.swing.JTextField();
        entradaPrecioMayor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        entradaEstiloFiltro = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cargarPuertas = new javax.swing.JLabel();
        cargarTransmision = new javax.swing.JLabel();
        cargarMaletas = new javax.swing.JLabel();
        cargarMPG = new javax.swing.JLabel();
        cargarColor = new javax.swing.JLabel();
        cargarCapacidad = new javax.swing.JLabel();
        cargarVIN = new javax.swing.JLabel();
        cargarAño = new javax.swing.JLabel();
        cargarMarca = new javax.swing.JLabel();
        cargarKilometraje = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cargarCedulaReserva = new javax.swing.JLabel();
        cargarSedeR = new javax.swing.JLabel();
        cargarSedeE = new javax.swing.JLabel();
        cargarPlacaReserva = new javax.swing.JLabel();
        cargarCostoReserva = new javax.swing.JLabel();
        cargarFechaR = new javax.swing.JLabel();
        cargarFechaE = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        cargarTipoCambioFecha = new javax.swing.JLabel();
        cargarTipoCambioCompra = new javax.swing.JLabel();
        cargarTipoCambioVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reserva");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula del Cliente:");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entradaCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("clienteReserva", jPanel1);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cliente Encontrado");

        jLabel4.setText("Cédula:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Primer Apellido:");

        jLabel7.setText("Segundo Apellido:");

        jLabel8.setText("Correo:");

        jLabel9.setText("Telefono:");

        jLabel10.setText("idProvincia:");

        jLabel11.setText("idCanton");

        jLabel12.setText("idDistrito:");

        jLabel13.setText("señas:");

        resultadoCedula.setText("jLabel12");

        resultadoNombre.setText("jLabel13");

        resultadoApellido1.setText("jLabel14");

        resultadoApellido2.setText("jLabel15");

        resultadoCorreo.setText("jLabel16");

        resultadoTelefono.setText("jLabel17");

        resultadoProvincia.setText("jLabel18");

        resultadoCanton.setText("jLabel19");

        resultadoDistrito.setText("jLabel20");

        resultadoSeñas.setText("jLabel21");

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Foto de la Licencia:");

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(130, 130, 130))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(resultadoNombre)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoApellido1))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoTelefono))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoCedula))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoApellido2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultadoDistrito)
                                    .addComponent(resultadoSeñas)
                                    .addComponent(resultadoProvincia)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(resultadoCanton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(86, 86, 86)
                        .addComponent(resultadoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(555, 555, 555))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(resultadoCedula)
                    .addComponent(resultadoProvincia))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(resultadoNombre)
                    .addComponent(jLabel11)
                    .addComponent(resultadoCanton))
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(resultadoApellido1)
                    .addComponent(jLabel12)
                    .addComponent(resultadoDistrito))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(resultadoApellido2)
                    .addComponent(jLabel13)
                    .addComponent(resultadoSeñas))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(resultadoCorreo))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9)
                    .addComponent(resultadoTelefono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("resultadoCliente", jPanel2);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sede de Entrega:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sede de Recogida:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fechas");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sedes y Fechas");

        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Servicios Adicionales");

        entradaWifi.setText("WiFi Ilimitado / $15 diarios");

        entradaAsistencia.setText("Asistencia en Carretera / $3.99 diarios");

        entradaAsiento.setText("Asiento para Niño / $6.99 diarios");

        entradaCobertura.setText("Cobertura por daños a terceros / $12.99 diarios");
        entradaCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCoberturaActionPerformed(evt);
            }
        });

        entradaGPS.setText("GPS / $13.99 diarios");

        entradaSedeRecogida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        entradaSedeRecogida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaSedeRecogidaActionPerformed(evt);
            }
        });

        entradaSedeEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(41, 41, 41))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaSedeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaSedeRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaFechaRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(entradaGPS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(entradaAsistencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(entradaWifi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel19)))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(entradaAsiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(entradaCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel18))))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel19))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel18)))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(entradaSedeRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(entradaFechaRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(entradaSedeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(entradaFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaWifi)
                    .addComponent(entradaAsiento))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaAsistencia)
                    .addComponent(entradaCobertura))
                .addGap(33, 33, 33)
                .addComponent(entradaGPS)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("sedeFechaReserva", jPanel3);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Seleccionar Vehiculo");

        jLabel21.setText("Estilo de Vehiculo:");

        jLabel22.setText("Capacidad:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "ID Estilo", "Costo por día"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel23.setText("Precio de menor:");

        entradaPrecioMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPrecioMenorActionPerformed(evt);
            }
        });

        entradaPrecioMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPrecioMayorActionPerformed(evt);
            }
        });

        jLabel24.setText("a mayor:");

        jButton6.setText("Ver detalle de Vehiculo Seleccionado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setText("Limpiar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(97, 613, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(248, 248, 248))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaEstiloFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCapacidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(entradaPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel24)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(entradaPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(entradaEstiloFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(entradaPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(entradaPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaCapacidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("vehiculoReserva", jPanel5);

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Detalle de Vehículo Seleccionado");

        jLabel38.setText("Número de Puertas:");

        jLabel39.setText("Tipo de Transmisión:");

        jLabel40.setText("Cantidad de Maletas:");

        jLabel41.setText("MPG:");

        jLabel42.setText("Capacidad:");

        jLabel43.setText("Número de VIN:");

        jLabel44.setText("Año:");

        jLabel45.setText("Color:");

        jLabel46.setText("Marca:");

        jLabel47.setText("Kilometraje:");

        cargarPuertas.setText("jLabel48");

        cargarTransmision.setText("jLabel49");

        cargarMaletas.setText("jLabel50");

        cargarMPG.setText("jLabel51");

        cargarColor.setText("jLabel52");

        cargarCapacidad.setText("jLabel53");

        cargarVIN.setText("jLabel54");

        cargarAño.setText("jLabel55");

        cargarMarca.setText("jLabel56");

        cargarKilometraje.setText("jLabel57");

        jButton8.setText("Volver a los Vehiculos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Continuar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel37))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel45))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarColor)
                            .addComponent(cargarMPG)
                            .addComponent(cargarMaletas)
                            .addComponent(cargarTransmision)
                            .addComponent(cargarPuertas))
                        .addGap(178, 178, 178)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarKilometraje)
                            .addComponent(cargarMarca)
                            .addComponent(cargarAño)
                            .addComponent(cargarVIN)
                            .addComponent(cargarCapacidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jButton8))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel42)
                    .addComponent(cargarPuertas)
                    .addComponent(cargarCapacidad)
                    .addComponent(jButton9))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel43)
                            .addComponent(cargarVIN)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cargarTransmision)))
                .addGap(51, 51, 51)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel44)
                    .addComponent(cargarMaletas)
                    .addComponent(cargarAño))
                .addGap(67, 67, 67)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel46)
                    .addComponent(cargarMPG)
                    .addComponent(cargarMarca))
                .addGap(84, 84, 84)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47)
                    .addComponent(cargarColor)
                    .addComponent(cargarKilometraje))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("detalleVehiculo", jPanel11);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Detalle de la Reserva");

        jLabel26.setText("Cedula del Cliente:");

        jLabel27.setText("Sede de Entrega:");

        jLabel28.setText("Sede de Recogida:");

        jLabel29.setText("Fecha:");

        jLabel30.setText("Fecha:");

        jLabel31.setText("Placa del Vehiculo:");

        jLabel32.setText("CostoTotal:");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tipo de Cambio del Dólar");

        jLabel34.setText("Compra:");

        jLabel35.setText("Venta:");

        cargarCedulaReserva.setText("jLabel12");

        cargarSedeR.setText("jLabel13");

        cargarSedeE.setText("jLabel14");

        cargarPlacaReserva.setText("jLabel15");

        cargarCostoReserva.setText("jLabel16");

        cargarFechaR.setText("jLabel17");

        cargarFechaE.setText("jLabel18");

        jButton7.setText("Confirmar Reserva");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel49.setText("Fecha:");

        cargarTipoCambioFecha.setText(webServiceTipoCambio.getTipoCambioFecha());

        cargarTipoCambioCompra.setText(Float.toString(webServiceTipoCambio.getTipoCambioCompra()));

        cargarTipoCambioVenta.setText(Float.toString(webServiceTipoCambio.getTipoCambioVenta()));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cargarTipoCambioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addComponent(jLabel49))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cargarTipoCambioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cargarTipoCambioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel33))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(cargarCedulaReserva)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarSedeR)
                            .addComponent(cargarSedeE)
                            .addComponent(cargarCostoReserva)
                            .addComponent(cargarPlacaReserva))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(39, 39, 39)
                                .addComponent(cargarFechaE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargarFechaR)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(134, 134, 134))))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cargarCedulaReserva))
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(cargarSedeR)
                    .addComponent(cargarFechaR))
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(cargarSedeE)
                    .addComponent(cargarFechaE))
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cargarPlacaReserva))
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cargarCostoReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cargarTipoCambioFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cargarTipoCambioCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cargarTipoCambioVenta))
                .addGap(23, 23, 23))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("detalleReserva", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (entradaCedulaReserva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del cliente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            cedulaReserva = entradaCedulaReserva.getText();
            res = Conexiones.Conexion.consulta("Select COUNT(cedula) from esquema.Cliente where cedula='" + Integer.parseInt(cedulaReserva) + "'");
            try {

                while (res.next()) {
                    cont = res.getInt(1);

                }

                if (cont >= 0) {
                    res = Conexiones.Conexion.consulta("Select * from esquema.Cliente where cedula='" + cedulaReserva + "'");
                    try {
                        while (res.next()) {
                            resultadoCedula.setText((res.getString(1)));
                            resultadoNombre.setText(res.getString(2));
                            resultadoApellido1.setText(res.getString(3));
                            resultadoApellido2.setText(res.getString(4));
                            resultadoCorreo.setText(res.getString(5));
                            resultadoTelefono.setText((res.getString(6)));
                            resultadoProvincia.setText(res.getString(7));
                            resultadoCanton.setText(res.getString(8));
                            resultadoDistrito.setText(res.getString(9));
                            resultadoSeñas.setText(res.getString(10));
                        }
                    } catch (SQLException e) {
                    }
                    panelPrincipal.setSelectedIndex(1);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "No existe ese cliente, revise el dato ingresado", "Error", JOptionPane.PLAIN_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if ((entradaSedeRecogida.getSelectedItem().toString()).equals("") || (entradaSedeEntrega.getSelectedItem().toString()).equals("") || entradaFechaRecogida.getDate() == null || entradaFechaEntrega.getDate() == null) {
            JOptionPane.showMessageDialog(null, "No se han completado todos los datos", "Error", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                copiaSedeRecogida = entradaSedeRecogida.getSelectedItem().toString();
                copiaSedeEntrega = entradaSedeEntrega.getSelectedItem().toString();
                copiaFechaRecogida = entradaFechaRecogida.getDate();
                copiaFecha1 = new java.sql.Date(copiaFechaRecogida.getTime());
                copiaFechaR = copiaFecha1.toString();
                copiaFechaEntrega = entradaFechaEntrega.getDate();
                copiaFecha2 = new java.sql.Date(copiaFechaEntrega.getTime());
                copiaFechaE = copiaFecha2.toString();
                Calendar hoy = Calendar.getInstance(); //obtiene la fecha actual
                int anio = hoy.get(Calendar.YEAR);
                int mes = hoy.get(Calendar.MONTH);
                int dia = hoy.get(Calendar.DATE);
                java.sql.Date copiaFechaS = new java.sql.Date(anio, mes, dia);
                java.sql.Date copiaFecha3 = new java.sql.Date(copiaFechaS.getTime());
                copiaFechaE = copiaFecha3.toString();
                if (entradaWifi.isSelected()) {
                    costoTotal = (float) (costoTotal + 15.00);
                } else if (entradaAsistencia.isSelected()) {
                    costoTotal = (float) (costoTotal + 3.99);
                } else if (entradaGPS.isSelected()) {
                    costoTotal = (float) (costoTotal + 13.99);
                } else if (entradaAsiento.isSelected()) {
                    costoTotal = (float) (costoTotal + 6.99);
                } else if (entradaCobertura.isSelected()) {
                    costoTotal = (float) (costoTotal + 12.99);
                }

                JOptionPane.showMessageDialog(null, "Se han ingresado los datos correctamente", "ÉXITO", JOptionPane.PLAIN_MESSAGE);
                panelPrincipal.setSelectedIndex(3);
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "No se ha podido ingresar los datos", "Error", JOptionPane.PLAIN_MESSAGE);

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        modelo2.setRowCount(0);

        if (entradaPrecioMenor.getText().equals("") && entradaPrecioMayor.getText().equals("") && entradaEstiloFiltro.getText().equals("") && entradaCapacidadFiltro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error al realizar la busqueda, ingrese los filtros deseados", "Error de ingreso", JOptionPane.PLAIN_MESSAGE);
        } else {
            //Filtro solo por la el estilo de Vehiculo
            if (!"".equals(entradaEstiloFiltro.getText()) && entradaPrecioMenor.getText().equals("") && entradaCapacidadFiltro.getText().equals("") && entradaPrecioMayor.getText().equals("")) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "' and idEstilo='" + Integer.parseInt(entradaEstiloFiltro.getText()) + "'");
                try {
                    while (res.next()) {
                        Vector v = new Vector();

                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {
                    System.out.println(e);

                }

            }
            //Filtro de solo la Capacidad del Vehiculo
            if (!"".equals(entradaCapacidadFiltro.getText()) && entradaPrecioMenor.getText().equals("") && entradaEstiloFiltro.getText().equals("") && entradaPrecioMayor.getText().equals("")) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "' and capacidadPersonas='" + Integer.parseInt(entradaCapacidadFiltro.getText()) + "'");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            } //Filtro solo del precio
            else if (!"".equals(entradaPrecioMenor.getText()) && !"".equals(entradaPrecioMayor.getText()) && entradaCapacidadFiltro.getText().equals("") && entradaEstiloFiltro.getText().equals("")) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "' and costoDia between '" + Integer.parseInt(entradaPrecioMenor.getText()) + "' and '" + Integer.parseInt(entradaPrecioMayor.getText()) + "' order by costoDia asc");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            } //Filtro solo estilo y precio
            else if (!"".equals(entradaPrecioMenor.getText()) && !"".equals(entradaPrecioMayor.getText()) && entradaCapacidadFiltro.getText().equals("") && !"".equals(entradaEstiloFiltro.getText())) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "'and idEstilo='" + Integer.parseInt(entradaEstiloFiltro.getText()) + "' and costoDia between '" + Integer.parseInt(entradaPrecioMenor.getText()) + "' and '" + Integer.parseInt(entradaPrecioMayor.getText()) + "' order by costoDia asc");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            } //Filtro estilo y capacidad
            else if (!"".equals(entradaCapacidadFiltro.getText()) && entradaPrecioMenor.getText().equals("") && entradaPrecioMayor.getText().equals("") && !"".equals(entradaEstiloFiltro.getText())) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "'and idEstilo='" + Integer.parseInt(entradaEstiloFiltro.getText()) + "' and capacidadPersonas= '" + Integer.parseInt(entradaCapacidadFiltro.getText()) + "'");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            } //Filtro capacidad y precio
            else if (!"".equals(entradaPrecioMenor.getText()) && !"".equals(entradaPrecioMayor.getText()) && !"".equals(entradaCapacidadFiltro.getText()) && entradaEstiloFiltro.getText().equals("")) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "'and capacidadPersonas='" + Integer.parseInt(entradaCapacidadFiltro.getText()) + "' and costoDia between '" + Integer.parseInt(entradaPrecioMenor.getText()) + "' and '" + Integer.parseInt(entradaPrecioMayor.getText()) + "' order by costoDia asc");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            } //Todos los filtros
            else if (!"".equals(entradaPrecioMenor.getText()) && !"".equals(entradaPrecioMayor.getText()) && !"".equals(entradaCapacidadFiltro.getText()) && !"".equals(entradaEstiloFiltro.getText())) {
                res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where idSede='" + copiaSedeRecogida + "'and capacidadPersonas='" + Integer.parseInt(entradaCapacidadFiltro.getText()) + "' and idEstilo=' " + Integer.parseInt(entradaCapacidadFiltro.getText()) + "' and costoDia between '" + Integer.parseInt(entradaPrecioMenor.getText()) + "' and '" + Integer.parseInt(entradaPrecioMayor.getText()) + "' order by costoDia asc");
                try {
                    while (res.next()) {
                        Vector v = new Vector();
                        v.add(res.getString(1));
                        v.add(res.getInt(15));
                        v.add(res.getFloat(3));
                        modelo2.addRow(v);
                        jTable1.setModel(modelo2);
                    }
                } catch (SQLException e) {

                }

            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void entradaPrecioMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPrecioMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPrecioMenorActionPerformed

    private void entradaPrecioMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPrecioMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPrecioMayorActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        String placa = jTable1.getValueAt(row, 0).toString();
        res = Conexiones.Conexion.consulta("Select * from esquema.Vehiculo where placa='" + placa + "'");
        copiaPlacaR = jTable1.getValueAt(row, 0).toString();
        costoTotal = costoTotal + Float.parseFloat(jTable1.getValueAt(row, 2).toString());
        try {
            while (res.next()) {

                cargarVIN.setText(res.getString(2));
                cargarAño.setText(res.getString(4));
                cargarCapacidad.setText(res.getString(5));
                cargarPuertas.setText(res.getString(6));
                cargarMaletas.setText(res.getString(7));
                cargarMPG.setText(res.getString(8));
                cargarKilometraje.setText(res.getString(9));
                cargarTransmision.setText(res.getString(11));
                cargarColor.setText(res.getString(12));
                cargarMarca.setText(res.getString(13));
                panelPrincipal.setSelectedIndex(4);
            }

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void entradaCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCoberturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCoberturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSelectedIndex(5);

        try {
            cargarCedulaReserva.setText(cedulaReserva);
            cargarSedeR.setText(copiaSedeRecogida);
            cargarSedeE.setText(copiaSedeEntrega);
            cargarFechaR.setText(copiaFechaR);
            cargarFechaE.setText(copiaFechaE);
            cargarPlacaReserva.setText(copiaPlacaR);
            cantidadDias = (int) (((copiaFechaRecogida.getTime() - copiaFechaEntrega.getTime()) / 86400000) * -1);
            costoReserva = cantidadDias * costoTotal;
            String costoString = String.valueOf(costoReserva);
            cargarCostoReserva.setText(costoString);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "No se pudo continuar con la reserva, vuelva a intentar", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            java.util.Date objDate = new Date();
            System.out.println(objDate);
            SimpleDateFormat fecha = new SimpleDateFormat("MM/dd/yyyy");
            String fechaSolicitud = fecha.format(objDate.getDate());

            Procedimientos.ingresarReserva(fechaSolicitud, copiaFechaR, copiaFechaE, copiaSedeRecogida, copiaSedeEntrega, cedulaReserva, copiaPlacaR, "1", "1");
            res = Conexiones.Conexion.consulta("select IDENT_CURRENT('esquema.Reserva')");
            while (res.next()) {
                idreserva = res.getInt(1);
            }

            Procedimientos.ingresarFactura(costoReserva, cedulaReserva, idreserva);
            res = Conexiones.Conexion.consulta("select IDENT_CURRENT('esquema.Factura')");
            while (res.next()) {
                idfactura = res.getInt(1);
            }

            res = Conexiones.Conexion.consulta("Select * from esquema.Cliente");
            while (res.next()) {
                if (res.getString(1).equals(cedulaReserva)) {
                    correoCliente = res.getString(5);
                }
            }

            informacionReserva = ("Cédula del cliente: " + "\t" + cedulaReserva + "\n" + "Número de Reserva: " + "\t" + idreserva + "\n" + "Número de Factura: " + "\t" + idfactura + "\n" + "Fecha de Solicitud: " + "\t" + fechaSolicitud + "\n" + "Sede Recogida: " + "\t" + copiaSedeRecogida + "\t\t" + "Fecha Recogida: " + "\t" + copiaFechaR + "\n"
                    + "Sede Entrega: " + "\t" + copiaSedeEntrega + "\t\t" + "Fecha Entrega: " + "\t" + copiaFechaR + "\n" + "Placa Vehículo:" + "\t" + copiaPlacaR + "\n" + "Costo Total de la Reserva:" + "\t" + costoReserva + "\n");

            PDF.crearPDF(informacionReserva, correoCliente);

            PrintPDF.printDocument();

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(interfazReservaCompleta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(interfazReservaCompleta.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        while (modelo2.getRowCount() > 0) {
            modelo2.removeRow(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void entradaSedeRecogidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaSedeRecogidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaSedeRecogidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazReservaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazReservaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazReservaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazReservaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazReservaCompleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargarAño;
    private javax.swing.JLabel cargarCapacidad;
    private javax.swing.JLabel cargarCedulaReserva;
    private javax.swing.JLabel cargarColor;
    private javax.swing.JLabel cargarCostoReserva;
    private javax.swing.JLabel cargarFechaE;
    private javax.swing.JLabel cargarFechaR;
    private javax.swing.JLabel cargarKilometraje;
    private javax.swing.JLabel cargarMPG;
    private javax.swing.JLabel cargarMaletas;
    private javax.swing.JLabel cargarMarca;
    private javax.swing.JLabel cargarPlacaReserva;
    private javax.swing.JLabel cargarPuertas;
    private javax.swing.JLabel cargarSedeE;
    private javax.swing.JLabel cargarSedeR;
    private javax.swing.JLabel cargarTipoCambioCompra;
    private javax.swing.JLabel cargarTipoCambioFecha;
    private javax.swing.JLabel cargarTipoCambioVenta;
    private javax.swing.JLabel cargarTransmision;
    private javax.swing.JLabel cargarVIN;
    private javax.swing.JCheckBox entradaAsiento;
    private javax.swing.JCheckBox entradaAsistencia;
    private javax.swing.JTextField entradaCapacidadFiltro;
    private javax.swing.JTextField entradaCedulaReserva;
    private javax.swing.JCheckBox entradaCobertura;
    private javax.swing.JTextField entradaEstiloFiltro;
    private com.toedter.calendar.JDateChooser entradaFechaEntrega;
    private com.toedter.calendar.JDateChooser entradaFechaRecogida;
    private javax.swing.JCheckBox entradaGPS;
    private javax.swing.JTextField entradaPrecioMayor;
    private javax.swing.JTextField entradaPrecioMenor;
    private javax.swing.JComboBox<String> entradaSedeEntrega;
    private javax.swing.JComboBox<String> entradaSedeRecogida;
    private javax.swing.JCheckBox entradaWifi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane panelPrincipal;
    public static javax.swing.JLabel resultadoApellido1;
    public static javax.swing.JLabel resultadoApellido2;
    public static javax.swing.JLabel resultadoCanton;
    public static javax.swing.JLabel resultadoCedula;
    public static javax.swing.JLabel resultadoCorreo;
    public static javax.swing.JLabel resultadoDistrito;
    public static javax.swing.JLabel resultadoNombre;
    public static javax.swing.JLabel resultadoProvincia;
    public static javax.swing.JLabel resultadoSeñas;
    public static javax.swing.JLabel resultadoTelefono;
    // End of variables declaration//GEN-END:variables
}
